### PR TITLE
Add soft deletes to load gen

### PR DESCRIPTION
**Pull request by dehume**
Addition to the load to remove a random number of purchases and change to the data model
Demo ERD

NOTE: This probably won't play well with https://github.com/MaterializeInc/demos/pull/50 since unless it's changed to update rows one at a time and at random, this part of the loop won't be reached.

### CODE REVIEW

**Review by joacoc — APPROVED** [review]
LGTM.

**Review by bobbyiliev — APPROVED** [review]
Looks good! I think that this should also work fine with the actual delete statements from #50 as those will only be used to keep the volume of the data in the MySQL database low

**Review by morsapaes — APPROVED** [review]
👍 

Left a comment in #50; I think we should handle MySQL data cleanup in a different script to separate concerns.

**Comment by bobbyiliev** [comment]
Just updated #50 and moved the cleanup functionality to a separate script which we could run on a daily basis via a corn job at midnight for example, eg: `0 0 * * * python3 /path/to/script.py`

**Comment by morsapaes** [comment]
<p align="center">
  
</p>

**Comment by morsapaes** [comment]
Can you address the pending conflicts and merge this in, @dehume?

**Pull request merged**
