### PR TITLE
Antennas Manhattan demo

### PR DESCRIPTION
**Pull request by joacoc**
Moving the antennas manhattan project to Materialize demo section!

### CODE REVIEW

**Comment by joacoc** [comment]
Oh... I just saw the CI test. I will need to add one.

**Comment by joacoc** [comment]
Oops. My bad! Thank you @morsapaes

**Comment by joacoc** [comment]
@morsapaes now looks ready!

**Review by morsapaes — APPROVED** [review]
That's...a lot of files. 😬  Is there any code that is "shared" between both directories (_e.g._ `/frontend`) that could be cross-referenced in one of the `compose.yaml` files? There's an example of what I mean [here](https://github.com/MaterializeInc/demos/blob/08aff294a7727dac4a5cf0efa45775fd51adf823/ecommerce-redpanda/compose.yaml#L72).

If there's room to tidy things up, you can shuffle things around in a follow-up PR, not a blocker! Thanks for pushing this in, LGTM.

**Comment by joacoc** [comment]
Yes! The `/frontend` could be shared. The other parts like `back-end` or `helpers` could be refactored to be reused.
I'm going to push the `/frontend` change and if the other parts should also be resued, let me know!
(Happy to modify them and push them if another PR 🙌)

**Pull request merged**
